### ISSUE TITLE
interrupt interpreter?

### ISSUE THREAD

**Issue by kaspar030** [embive/embive#1]
Is there a way to interrupt the engine? Or trigger interrupts?

We'd like to use it for testing our rtos, that would need some way of doing external flow 
control.

**edit** Oh, first issue and it is already shouting "do more work!". Sorry for that. So, first this:
I stumbled over this and find it extremely interesting. Thanks a lot for doing all the work!
Looking forward to using and contributing to embive!

**Comment by danielstuart14** [comment]
Hi there!
Currently we don't support any type of external interrupts; this is probably something that will have to happen for callbacks to be supported (which is on the roadmap), but I can't give you a timeline, unfortunately.

There are a couple of things blocking us right now: figuring out if we are going to support the full risc-v calling convention or just the SBI-like interface we have right now; if interrupts should happen right away or only when the engine is paused/halted (after an instruction limit, for example); etc.

Also, Embive was made from the ground up to support only the unprivileged spec, so any interrupt implementation would need to be based on the "N Extension" spec, which is different from how you would interact with interrupts on a real MCU.

For your use case, I'd probably suggest using a RISC-V simulator like [spike](https://github.com/riscv-software-src/riscv-isa-sim).

I'm closing this for now, but feel free to ask anything else!

Thanks!

**Comment by danielstuart14** [comment]
@kaspar030 interrupts are now implemented on the master branch!
Check the template repository for an example of how to use it.

**Comment by kaspar030** [comment]
Awesome, thanks! 👌
